version: '2'
services:
    java-assembly:
        container_name: java-assembly
        build:
            dockerfile: JavaAssemblyDockerFile
            args:
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_URL=$MYSQL_URL
        image: java-assembly:latest
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_URL=$MYSQL_URL
        ports:
            - 8080:8080
        depends_on:
         mysql-database:
          condition: service_healthy
        networks:
            - java-assembly-network
    mysql-database:
        container_name: mysql-database
        build:
            dockerfile: DatabaseDockerFile
            args:
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        image: mysql-database:latest
        ports:
            - 8090:3306
        healthcheck:
         test: ["CMD","mysqladmin","ping","-h","localhost"]
         timeout: 20s
         retries: 10
        networks:
            - java-assembly-network
networks:
    java-assembly-network:
        driver: bridge